import { config, library } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {
  faArrowRight,
  faBars,
  faBolt,
  faBookOpen,
  faBriefcase,
  faBullhorn,
  faCalendarDays,
  faChalkboardTeacher,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCirclePlay,
  faClapperboard,
  faClock,
  faCode,
  faCompass,
  faEnvelope,
  faEye,
  faGlobe,
  faGraduationCap,
  faHandshake,
  faHeart,
  faLandmark,
  faLaptopCode,
  faLightbulb,
  faLocationDot,
  faMagicWandSparkles,
  faMapMarkerAlt,
  faMicrophone,
  faMountainSun,
  faPaintBrush,
  faPalette,
  faPeopleGroup,
  faPhone,
  faPlay,
  faQuoteLeft,
  faRocket,
  faSchool,
  faSeedling,
  faStar,
  faTimes,
  faUsers,
  faVideo,
  faVrCardboard,
} from '@fortawesome/free-solid-svg-icons'
import {
  faInstagram,
  faLinkedin,
  faTwitter,
  faYoutube,
  faFacebook,
  faXTwitter,
} from '@fortawesome/free-brands-svg-icons'
import { faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons'

config.autoAddCss = false

library.add(
  faArrowRight, faBars, faBolt, faBookOpen, faBriefcase, faBullhorn,
  faCalendarDays, faChalkboardTeacher, faChartLine, faCheck, faChevronDown,
  faChevronRight, faCirclePlay, faClapperboard, faClock, faCode, faCompass,
  faEnvelope, faEye, faGlobe, faGraduationCap, faHandshake, faHeart,
  faLandmark, faLaptopCode, faLightbulb, faLocationDot, faMagicWandSparkles,
  faMagnifyingGlass, faMapMarkerAlt, faMicrophone, faMountainSun, faPaintBrush, faPalette,
  faPeopleGroup, faPhone, faPlay, faQuoteLeft, faRocket, faSchool,
  faSeedling, faStar, faTimes, faUsers, faVideo, faVrCardboard,
  faFacebook, faInstagram, faLinkedin, faTwitter, faXTwitter, faYoutube
)
