import { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRight,
  faBars,
  faBolt,
  faBookOpen,
  faBriefcase,
  faBullhorn,
  faCalendarDays,
  faChalkboardTeacher,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCirclePlay,
  faClapperboard,
  faClock,
  faCode,
  faCompass,
  faEnvelope,
  faEye,
  faGlobe,
  faGraduationCap,
  faHandshake,
  faHeart,
  faLandmark,
  faLaptopCode,
  faLightbulb,
  faLocationDot,
  faMagicWandSparkles,
  faMagnifyingGlass,
  faMapMarkerAlt,
  faMicrophone,
  faMountainSun,
  faPaintBrush,
  faPalette,
  faPeopleGroup,
  faPhone,
  faPlay,
  faQuoteLeft,
  faRocket,
  faSchool,
  faSeedling,
  faStar,
  faTimes,
  faUsers,
  faVideo,
  faVrCardboard,
} from '@fortawesome/free-solid-svg-icons'

export const iconMap: Record<string, IconDefinition> = {
  'arrow-right': faArrowRight,
  'bars': faBars,
  'bolt': faBolt,
  'book-open': faBookOpen,
  'briefcase': faBriefcase,
  'bullhorn': faBullhorn,
  'calendar-days': faCalendarDays,
  'chalkboard-teacher': faChalkboardTeacher,
  'chart-line': faChartLine,
  'check': faCheck,
  'chevron-down': faChevronDown,
  'chevron-right': faChevronRight,
  'circle-play': faCirclePlay,
  'clapperboard': faClapperboard,
  'clock': faClock,
  'code': faCode,
  'compass': faCompass,
  'envelope': faEnvelope,
  'eye': faEye,
  'globe': faGlobe,
  'graduation-cap': faGraduationCap,
  'handshake': faHandshake,
  'heart': faHeart,
  'landmark': faLandmark,
  'laptop-code': faLaptopCode,
  'lightbulb': faLightbulb,
  'location-dot': faLocationDot,
  'magic-wand-sparkles': faMagicWandSparkles,
  'magnifying-glass': faMagnifyingGlass,
  'map-marker-alt': faMapMarkerAlt,
  'microphone': faMicrophone,
  'mountain-sun': faMountainSun,
  'paint-brush': faPaintBrush,
  'palette': faPalette,
  'people-group': faPeopleGroup,
  'phone': faPhone,
  'play': faPlay,
  'quote-left': faQuoteLeft,
  'rocket': faRocket,
  'school': faSchool,
  'seedling': faSeedling,
  'star': faStar,
  'times': faTimes,
  'users': faUsers,
  'video': faVideo,
  'vr-cardboard': faVrCardboard,
}

export function resolveIcon(icon: string | IconDefinition): IconDefinition {
  if (typeof icon === 'string') {
    return iconMap[icon] || faQuoteLeft
  }
  return icon
}
