import { FontAwesomeIcon, FontAwesomeIconProps } from '@fortawesome/react-fontawesome'
import { IconDefinition } from '@fortawesome/fontawesome-svg-core'

// Solid icons
import {
  faCompass,
  faRocket,
  faHandshake,
  faGraduationCap,
  faFistRaised,
  faLink,
  faBridge,
  faCalendar,
  faStar,
  faArrowRight,
  faChevronLeft,
  faChevronRight,
  faMagnifyingGlass,
  faBars,
  faXmark,
  faHeart,
  faArrowTrendUp,
  faEnvelope,
  faPhone,
  faLocationDot,
  faClock,
  faPaperPlane,
  faUsers,
  faLightbulb,
  faChartLine,
  faBullhorn,
  faBuilding,
  faHandHoldingHeart,
  faGlobe,
  faBookOpen,
  faPalette,
  faLaptopCode,
  faCertificate,
  faNetworkWired,
  faSeedling,
  faMobileScreenButton,
  faDownload,
  faMapMarkedAlt,
  faVrCardboard,
  faLandmark,
  faMusic,
  faCamera,
  faFilm,
  faMicrophone,
  faChalkboardTeacher,
  faAward,
  faBriefcase,
  faCode,
  faVideo,
  faPencil,
  faQuoteLeft,
  faCheck,
} from '@fortawesome/free-solid-svg-icons'

// Brand icons
import {
  faFacebook,
  faXTwitter,
  faInstagram,
  faLinkedin,
} from '@fortawesome/free-brands-svg-icons'

// Map FA class names to icon definitions
const iconMap: Record<string, IconDefinition> = {
  'fa-solid fa-compass': faCompass,
  'fa-solid fa-rocket': faRocket,
  'fa-solid fa-handshake': faHandshake,
  'fa-solid fa-graduation-cap': faGraduationCap,
  'fa-solid fa-fist-raised': faFistRaised,
  'fa-solid fa-link': faLink,
  'fa-solid fa-bridge': faBridge,
  'fa-solid fa-calendar': faCalendar,
  'fa-solid fa-star': faStar,
  'fa-solid fa-arrow-right': faArrowRight,
  'fa-solid fa-chevron-left': faChevronLeft,
  'fa-solid fa-chevron-right': faChevronRight,
  'fa-solid fa-magnifying-glass': faMagnifyingGlass,
  'fa-solid fa-bars': faBars,
  'fa-solid fa-xmark': faXmark,
  'fa-solid fa-heart': faHeart,
  'fa-solid fa-arrow-trend-up': faArrowTrendUp,
  'fa-solid fa-envelope': faEnvelope,
  'fa-solid fa-phone': faPhone,
  'fa-solid fa-location-dot': faLocationDot,
  'fa-solid fa-clock': faClock,
  'fa-solid fa-paper-plane': faPaperPlane,
  'fa-solid fa-users': faUsers,
  'fa-solid fa-lightbulb': faLightbulb,
  'fa-solid fa-chart-line': faChartLine,
  'fa-solid fa-bullhorn': faBullhorn,
  'fa-solid fa-building': faBuilding,
  'fa-solid fa-hand-holding-heart': faHandHoldingHeart,
  'fa-solid fa-globe': faGlobe,
  'fa-solid fa-book-open': faBookOpen,
  'fa-solid fa-palette': faPalette,
  'fa-solid fa-laptop-code': faLaptopCode,
  'fa-solid fa-certificate': faCertificate,
  'fa-solid fa-network-wired': faNetworkWired,
  'fa-solid fa-seedling': faSeedling,
  'fa-solid fa-mobile-screen-button': faMobileScreenButton,
  'fa-solid fa-download': faDownload,
  'fa-solid fa-map-marked-alt': faMapMarkedAlt,
  'fa-solid fa-vr-cardboard': faVrCardboard,
  'fa-solid fa-landmark': faLandmark,
  'fa-solid fa-music': faMusic,
  'fa-solid fa-camera': faCamera,
  'fa-solid fa-film': faFilm,
  'fa-solid fa-microphone': faMicrophone,
  'fa-solid fa-chalkboard-teacher': faChalkboardTeacher,
  'fa-solid fa-award': faAward,
  'fa-solid fa-briefcase': faBriefcase,
  'fa-solid fa-code': faCode,
  'fa-solid fa-video': faVideo,
  'fa-solid fa-pencil': faPencil,
  'fa-solid fa-quote-left': faQuoteLeft,
  'fa-solid fa-check': faCheck,
  'fa-brands fa-facebook': faFacebook,
  'fa-brands fa-x-twitter': faXTwitter,
  'fa-brands fa-instagram': faInstagram,
  'fa-brands fa-linkedin': faLinkedin,
}

interface FaIconProps extends Omit<FontAwesomeIconProps, 'icon'> {
  iconClass: string
}

export default function FaIcon({ iconClass, ...props }: FaIconProps) {
  const icon = iconMap[iconClass]
  if (!icon) return null
  return <FontAwesomeIcon icon={icon} {...props} />
}

export { iconMap }
